### ISSUE TITLE
httpx.ConnectTimeout: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by 3201755129** [LYiHub/psydraw#2]
自己写了一版提示词，用的linux.do 社区的api,每次提交后过了两分半钟就会Retrying request，两次Retrying request之后就会产生如下超时报错。
2024-12-21 17:50:17,748 - INFO - HTPModel initialized with text model: claude-3-5-sonnet-20240620, multimodal model: gpt-4o-2024-08-06, language: zh
2024-12-21 17:50:17,749 - INFO - Cache enabled.
2024-12-21 17:50:17,786 - INFO - overall analysis started.
2024-12-21 17:50:17,786 - INFO - house analysis started.
2024-12-21 17:50:17,787 - INFO - tree analysis started.
2024-12-21 17:50:17,796 - INFO - person analysis started.
2024-12-21 17:52:45,075 - INFO - Retrying request to /chat/completions in 0.865885 seconds
2024-12-21 17:52:45,075 - INFO - Retrying request to /chat/completions in 0.822764 seconds
2024-12-21 17:52:45,075 - INFO - Retrying request to /chat/completions in 0.759759 seconds
2024-12-21 17:52:45,090 - INFO - Retrying request to /chat/completions in 0.868117 seconds
2024-12-21 17:55:13,116 - INFO - Retrying request to /chat/completions in 1.975761 seconds
2024-12-21 17:55:13,161 - INFO - Retrying request to /chat/completions in 1.968260 seconds
2024-12-21 17:55:13,208 - INFO - Retrying request to /chat/completions in 1.712306 seconds
2024-12-21 17:55:13,240 - INFO - Retrying request to /chat/completions in 1.843092 seconds
2024-12-21 17:57:42.416 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
    yield
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 256, in handle_request
    raise exc from None
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 101, in handle_request
    raise exc
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 78, in handle_request
    stream = self._connect(request)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_backends\sync.py", line 207, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 978, in _request
    response = self._client.send(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 926, in send
    response = self._send_handling_auth(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\ai\psydraw\src\pages\HTP Test.py", line 331, in <module>
    main()
  File "C:\ai\psydraw\src\pages\HTP Test.py", line 327, in main
    sidebar(model)
  File "C:\ai\psydraw\src\pages\HTP Test.py", line 242, in sidebar
    analyze_image(model)
  File "C:\ai\psydraw\src\pages\HTP Test.py", line 154, in analyze_image
    response = model.workflow(**inputs)
  File "C:\ai\psydraw\src\model_langchain.py", line 302, in workflow
    feature_result, analysis_result = future.result()
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\ai\psydraw\src\model_langchain.py", line 163, in basic_analysis
    feature_result = chain.invoke({
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\runnables\base.py", line 3022, in invoke
    input = context.run(step.invoke, input, config)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\chat_models.py", line 284, in invoke
    self.generate_prompt(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\chat_models.py", line 784, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\chat_models.py", line 641, in generate
    raise e
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\chat_models.py", line 631, in generate
    self._generate_with_cache(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\chat_models.py", line 853, in _generate_with_cache
    result = self._generate(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_openai\chat_models\base.py", line 670, in _generate
    response = self.client.create(**payload)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\resources\chat\completions.py", line 704, in create
    return self._post(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 1265, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 942, in request
    return self._request(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 987, in _request
    return self._retry_request(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 1080, in _retry_request
    return self._request(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 987, in _request
    return self._retry_request(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 1080, in _retry_request
    return self._request(
  File "C:\Users\32017\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 997, in _request
    raise APITimeoutError(request=request) from err
openai.APITimeoutError: Request timed out.
补充信息：系统为windows 11；代理使用情况：由于api限制，没有开启clash的代理功能（开启后无法使用api）。

**Comment by 3201755129** [comment]
windows 11由于api限制，没有开启clash的代理功能。

**Comment by 3201755129** [comment]
曾参考[解决使用Auto-GPT本地部署时无法连接Google的问题和无法连接openai的问题](https://blog.csdn.net/weixin_43744732/article/details/130190697)尝试解决，完成设置并开启代理后api会报错，无法使用
曾尝试使用自己申请的免费官网api，结合clash代理解决访问问题，但报错更快了，包括error connection,Request timed out, 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}

**Comment by ZhangYiqun018** [comment]
需要找你模型服务商解决该问题
